name: Deploy to Server Rsync

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create clean deployment folder
      run: |
        # Создаем чистую папку для деплоя
        mkdir -p deploy_folder
        
        # Копируем все содержимое, кроме исключенных папок/файлов
        rsync -av \
          --exclude='.git' \
          --exclude='.github' \
          --exclude='.gitignore' \
          --exclude='nginx.conf' \
          --exclude='docker-compose.yml' \
          --exclude='Dockerfile-php' \
          --exclude='*.log' \
          --exclude='app/config.php' \
          ./ deploy_folder/
        
        echo "Deployment folder created:"
        ls -la deploy_folder/

    - name: Deploy folder via SCP
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "deploy_folder/*"
        target: "/home/webwell/server/www/wellnessexpert"
        overwrite: true
        strip_components: 1