name: Twelve Workflow
on: [push]

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    environment: "staging"
    steps:
      - name: Our Vars and Secrets
        run: |
          echo '${{ vars.STATUS }}'
          echo '${{ secrets.PASSWORD }}'
          


